### ISSUE TITLE
Loop increment incorrectly modified by eliminate-local-multi-store

### ISSUE THREAD

**Issue by tafuri** [KhronosGroup/SPIRV-Tools#1228]
Optimizing the following shader with --eliminate-local-multi-store:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 108
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 1 1 1
               OpName %type_2d_image_array "type.2d.image.array"
               OpName %Output "Output"
               OpName %type_Constants "type.Constants"
               OpMemberName %type_Constants 0 "ConstantA"
               OpName %var_Constants "var.Constants"
               OpName %main "main"
               OpMemberDecorate %type_Constants 0 Offset 0
               OpDecorate %type_Constants Block
               OpDecorate %Output DescriptorSet 0
               OpDecorate %Output Binding 0
               OpDecorate %var_Constants DescriptorSet 0
               OpDecorate %var_Constants Binding 1
      %float = OpTypeFloat 32
%type_2d_image_array = OpTypeImage %float 2D 0 1 0 2 Rgba32f
%_ptr_UniformConstant_type_2d_image_array = OpTypePointer UniformConstant %type_2d_image_array
        %int = OpTypeInt 32 1
%type_Constants = OpTypeStruct %int
%_ptr_Uniform_type_Constants = OpTypePointer Uniform %type_Constants
       %void = OpTypeVoid
         %11 = OpTypeFunction %void
    %v4float = OpTypeVector %float 4
%_ptr_Function_v4float = OpTypePointer Function %v4float
%_ptr_Function_int = OpTypePointer Function %int
      %int_0 = OpConstant %int 0
       %bool = OpTypeBool
      %int_6 = OpConstant %int 6
      %int_1 = OpConstant %int 1
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
     %uint_0 = OpConstant %uint 0
         %52 = OpConstantComposite %v3uint %uint_0 %uint_0 %uint_0
    %float_0 = OpConstant %float 0
         %58 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
%_ptr_Uniform_int = OpTypePointer Uniform %int
     %Output = OpVariable %_ptr_UniformConstant_type_2d_image_array UniformConstant
%var_Constants = OpVariable %_ptr_Uniform_type_Constants Uniform
      %false = OpConstantFalse %bool
       %main = OpFunction %void None %11
         %13 = OpLabel
         %95 = OpVariable %_ptr_Function_v4float Function
         %68 = OpVariable %_ptr_Function_v4float Function
         %69 = OpVariable %_ptr_Function_int Function
         %71 = OpVariable %_ptr_Function_int Function
               OpStore %69 %int_0
               OpBranch %72
         %72 = OpLabel
         %73 = OpLoad %int %69
         %74 = OpSLessThan %bool %73 %int_6
               OpLoopMerge %75 %76 None
               OpBranchConditional %74 %77 %75
         %77 = OpLabel
               OpBranch %96
         %96 = OpLabel
               OpLoopMerge %97 %98 None
               OpBranch %99
         %99 = OpLabel
        %100 = OpAccessChain %_ptr_Uniform_int %var_Constants %int_0
        %101 = OpLoad %int %100
        %102 = OpSGreaterThanEqual %bool %int_1 %101
               OpSelectionMerge %103 None
               OpBranchConditional %102 %104 %103
        %104 = OpLabel
               OpStore %95 %58
               OpBranch %97
        %103 = OpLabel
               OpStore %95 %58
               OpBranch %97
         %98 = OpLabel
               OpBranchConditional %false %96 %97
         %97 = OpLabel
         %78 = OpLoad %v4float %95
               OpStore %71 %int_0
               OpBranch %79
         %79 = OpLabel
         %80 = OpLoad %int %71
         %81 = OpSLessThan %bool %80 %int_6
               OpLoopMerge %82 %83 None
               OpBranchConditional %81 %84 %82
         %84 = OpLabel
         %86 = OpLoad %v4float %68
         %87 = OpFAdd %v4float %86 %78
               OpStore %68 %87
               OpBranch %83
         %83 = OpLabel
         %88 = OpLoad %int %71
         %89 = OpIAdd %int %88 %int_1
               OpStore %71 %89
               OpBranch %79
         %82 = OpLabel
               OpBranch %76
         %76 = OpLabel
         %90 = OpLoad %int %69
         %91 = OpIAdd %int %90 %int_1
               OpStore %69 %91
               OpBranch %72
         %75 = OpLabel
         %92 = OpLoad %v4float %68
         %93 = OpLoad %type_2d_image_array %Output
               OpImageWrite %93 %52 %92
               OpReturn
               OpFunctionEnd
```

Generates the following result:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 121
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 1 1 1
               OpName %type_2d_image_array "type.2d.image.array"
               OpName %Output "Output"
               OpName %type_Constants "type.Constants"
               OpMemberName %type_Constants 0 "ConstantA"
               OpName %var_Constants "var.Constants"
               OpName %main "main"
               OpMemberDecorate %type_Constants 0 Offset 0
               OpDecorate %type_Constants Block
               OpDecorate %Output DescriptorSet 0
               OpDecorate %Output Binding 0
               OpDecorate %var_Constants DescriptorSet 0
               OpDecorate %var_Constants Binding 1
      %float = OpTypeFloat 32
%type_2d_image_array = OpTypeImage %float 2D 0 1 0 2 Rgba32f
%_ptr_UniformConstant_type_2d_image_array = OpTypePointer UniformConstant %type_2d_image_array
        %int = OpTypeInt 32 1
%type_Constants = OpTypeStruct %int
%_ptr_Uniform_type_Constants = OpTypePointer Uniform %type_Constants
       %void = OpTypeVoid
         %11 = OpTypeFunction %void
    %v4float = OpTypeVector %float 4
%_ptr_Function_v4float = OpTypePointer Function %v4float
%_ptr_Function_int = OpTypePointer Function %int
      %int_0 = OpConstant %int 0
       %bool = OpTypeBool
      %int_6 = OpConstant %int 6
      %int_1 = OpConstant %int 1
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
     %uint_0 = OpConstant %uint 0
         %52 = OpConstantComposite %v3uint %uint_0 %uint_0 %uint_0
    %float_0 = OpConstant %float 0
         %58 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
%_ptr_Uniform_int = OpTypePointer Uniform %int
     %Output = OpVariable %_ptr_UniformConstant_type_2d_image_array UniformConstant
%var_Constants = OpVariable %_ptr_Uniform_type_Constants Uniform
      %false = OpConstantFalse %bool
        %108 = OpUndef %v4float
        %111 = OpUndef %int
       %main = OpFunction %void None %11
         %13 = OpLabel
               OpBranch %72
         %72 = OpLabel
        %109 = OpPhi %v4float %108 %13 %119 %76
        %110 = OpPhi %int %int_0 %13 %91 %76
        %112 = OpPhi %int %111 %13 %120 %76
        %113 = OpPhi %v4float %108 %13 %118 %76
         %74 = OpSLessThan %bool %110 %int_6
               OpLoopMerge %75 %76 None
               OpBranchConditional %74 %77 %75
         %77 = OpLabel
               OpBranch %96
         %96 = OpLabel
        %114 = OpPhi %v4float %113 %77 %108 %98
               OpLoopMerge %97 %98 None
               OpBranch %99
         %99 = OpLabel
        %100 = OpAccessChain %_ptr_Uniform_int %var_Constants %int_0
        %101 = OpLoad %int %100
        %102 = OpSGreaterThanEqual %bool %int_1 %101
               OpSelectionMerge %103 None
               OpBranchConditional %102 %104 %103
        %104 = OpLabel
               OpBranch %97
        %103 = OpLabel
               OpBranch %97
         %98 = OpLabel
               OpBranchConditional %false %96 %97
         %97 = OpLabel
        %115 = OpPhi %v4float %109 %104 %109 %103 %108 %98
        %116 = OpPhi %int %110 %104 %110 %103 %111 %98
        %117 = OpPhi %int %112 %104 %112 %103 %111 %98
        %118 = OpPhi %v4float %58 %104 %58 %103 %108 %98
               OpBranch %79
         %79 = OpLabel
        %119 = OpPhi %v4float %115 %97 %87 %83
        %120 = OpPhi %int %int_0 %97 %89 %83
         %81 = OpSLessThan %bool %120 %int_6
               OpLoopMerge %82 %83 None
               OpBranchConditional %81 %84 %82
         %84 = OpLabel
         %87 = OpFAdd %v4float %119 %118
               OpBranch %83
         %83 = OpLabel
         %89 = OpIAdd %int %120 %int_1
               OpBranch %79
         %82 = OpLabel
               OpBranch %76
         %76 = OpLabel
         %91 = OpIAdd %int %116 %int_1
               OpBranch %72
         %75 = OpLabel
         %93 = OpLoad %type_2d_image_array %Output
               OpImageWrite %93 %52 %109
               OpReturn
               OpFunctionEnd
```

Note that the line `%91 = OpIAdd %int %90 %int_1` was transformed into `%91 = OpIAdd %int %116 %int_1` where `%116` is not actually the same variable used in the comparison for the outer loop. This means that subsequent optimization steps will optimize away the `OpIAdd` causing the loop to never terminate.

**Comment by greg-lunarg** [comment]
I will claim this one.

**Comment by greg-lunarg** [comment]
Hi Sebastian. Thanks for the feedback, although I believe this transformation, while slightly convoluted, is correct.

You will see that %116 is created by a Phi function using values %110 and %111, although you will notice that the control path for %111 will never be executed. So %116 is essentially the value %110.

%110 is also a Phi value set at the top of the outer loop. Its inputs are the constant 0 and %91, the IAdd you mention. So %110 represents the value held in variable %69 in the original code that controls the outer loop. And you will see that in the optimized code that %110 is indeed the value that is tested in the outer loop.

Please let me know if you see a problem with my assessment.

**Comment by greg-lunarg** [comment]
I figured you were having a *real* problem somewhere :)

Are you using current top of tree? We were seeing this problem a few weeks ago but it was fixed.

**Comment by alan-baker** [comment]
Using top of trunk, it looks like CCP is still problematic. The CCP right after eliminate local multi store has the induction variable increment always producing 1 and propagates that 1 to the outer loop phi that is used in the exit condition test.

**Comment by tafuri** [comment]
Yes, it seems like the CCP step was the actual problem. I apparently was mistaken in thinking that eliminate-local-multi-store was the cause. I still find spir-v quite difficult to read sometimes :)

**Comment by alan-baker** [comment]
Smallest testcase I've found that still reproduces this error:
```
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %func "func" %in
%void = OpTypeVoid
%bool = OpTypeBool
%int = OpTypeInt 32 1
%false = OpConstantFalse %bool
%int0 = OpConstant %int 0
%int1 = OpConstant %int 1
%int6 = OpConstant %int 6
%int_ptr_Input = OpTypePointer Input %int
%in = OpVariable %int_ptr_Input Input
%undef = OpUndef %int
%functy = OpTypeFunction %void
%func = OpFunction %void None %functy
%1 = OpLabel
OpBranch %2
%2 = OpLabel
%outer_phi = OpPhi %int %int0 %1 %outer_add %15
%cond1 = OpSLessThanEqual %bool %outer_phi %int6
OpLoopMerge %3 %15 None
OpBranchConditional %cond1 %4 %3
%4 = OpLabel

%ld = OpLoad %int %in
%cond2 = OpSGreaterThanEqual %bool %int1 %ld
OpSelectionMerge %10 None
OpBranchConditional %cond2 %8 %9
%8 = OpLabel
OpBranch %10
%9 = OpLabel
OpBranch %10
%10 = OpLabel
%extra_phi = OpPhi %int %outer_phi %8 %outer_phi %9
OpBranch %11
%11 = OpLabel
%inner_phi = OpPhi %int %int0 %10 %inner_add %13
%cond3 = OpSLessThanEqual %bool %inner_phi %int6
OpLoopMerge %14 %13 None
OpBranchConditional %cond3 %12 %14
%12 = OpLabel
OpBranch %13
%13 = OpLabel
%inner_add = OpIAdd %int %inner_phi %int1
OpBranch %11
%14 = OpLabel
OpBranch %15
%15 = OpLabel
%outer_add = OpIAdd %int %extra_phi %int1
OpBranch %2
%3 = OpLabel
OpReturn
OpFunctionEnd
```
Removing any of the phis causes the problem to disappear.

**Comment by alan-baker** [comment]
This appears to be caused by #1143 or #1159 or a combination of the two. During the initial simulation, %outer_phi only has the initialization edge executable and appears to produce an interesting value. Once %15 is simulated %2 gets pushed to simulate again. This re-simulates %outer_phi. The SSA edge to %extra_phi are not added because phis do not cause phis to be simulated again. This prevents lattice from being updated for %extra_phi and %outer_add so they appear to have interesting results at the end of the entire simulation which causes us to propagate constants and end up with an infinite loop.

**Comment by alan-baker** [comment]
My gut says the original infinite loop shouldn't be a problem when transitioning down to Varying since marking an instruction as varying should prevent further simulation of that instruction and break a loop. So if you reach the bottom of the lattice you should still add all the SSA edges.

Need to think through this solution more thoroughly.

**Comment by s-perron** [comment]
That seems reasonable.  When a id goes from from interesting or not interesting to varying, all of the consumers of the id should be reprocessed.

**Comment by alan-baker** [comment]
Unnecessary for the fix, but still seems wrong: CCPPass::VisitPhi doesn't mark the instruction as varying if all inputs are varying. It instead thinks the result is interesting because they all meet at the same value.

**Comment by alan-baker** [comment]
Fixed in 1b46f7ecad32f99e0b28702505a192d7bf680bd7
